### ISSUE TITLE
Encountering infinite loop upon receiving repeat 429 TooManyRequestsResponses

### ISSUE THREAD

**Issue by ecagsx** [smartystreets/changelog#1]
com.smartystreets.api.RetrySender#send resets the counter variable upon receiving a response of type TooManyRequestsResponse, overriding the maxRetries. If the user continues to receive that same response type, there is no exit from the loop. Can someone advise a workaround so our application does not encounter an infinite loop?

**Comment by RyanLCox1** [comment]
The TooManyRequestsResponse isn't an error state, it means you're being rate limited and it will "eventually" clean up. If you are on a thread that is blocking though, that is a potential problem for your program though because that thread will not return until you are no longer being rate limited. You could make the call to com.smartystreets.api.RetrySender#send from a completable future and then wait for it to actually return a response. The completable future would allow your program to continue processing and being responsive.

If you have other questions or concerns, let's move those over to the java sdk project here:
[https://github.com/smartystreets/smartystreets-java-sdk](url)
